---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: number
  name: weight
  label: weight
- type: text
  name: description
  label: description
- type: list
  name: tags
  label: tags
- type: text
  name: externalUrl
  label: externalUrl
pages:
- content/projects/c-c-project-generator.md
